### ISSUE TITLE
mkdir: cannot create directory

### ISSUE THREAD

**Issue by josruirod** [fmalmeida/MpGAP#39]
Hi, so thanks again for the help. I'm slowly going through the pipeline in my hpc. It seems to be only a matter of specificying enviromental variables to make sure the root directoyry and /tmp/are not filled, and then allocating enough resources (cpus and memory).
So at last, it's doing the pilon processes, but I've encountered an error I wanted to ask you about. Maybe related to the pipeline not resuming properly even if -resume provided to the nextflow command?
![image](https://user-images.githubusercontent.com/29894090/182097599-17f72e02-336e-4955-842b-cdf2474cea17.png)

This may be related with the pipeline and not my system? Checking out the logs I see the same error, similar with other folders, such as "wtdbg2" instead of "flye". I guess for the different Pilon runs on the different assemblies? There maybe some mkdir or mv commands that should be forced to allow for replace existing files and resuming runs? Thanks!

**Comment by fmalmeida** [comment]
Hi @josruirod,

yes. It’s possible to adjust that to avoid this error, but, anyways, it should not have been happening because nextflow is supposed to create new workdirs when running again.

I will add in the `params-issue` branch the -p param to mkdir to avoid this error when dir exists and see if it helps.

**Comment by fmalmeida** [comment]
Can you show the tree structure of this workir me? You can run

`tree -L2 path-to-dir`

**Comment by josruirod** [comment]
Thanks for the quick support! I guessed nextflow -resume should deal with all of that, but the error is clearly pointing to the need of mkdir -p... weird bug. Anyhow, I assume you mean the workdir in my snapshot above. This is the structure:
![image](https://user-images.githubusercontent.com/29894090/182125256-c994e0fd-55ac-4b55-b794-02f9f91bf5e0.png)

Maybe it's been modified because I relaunched the pipeline just in case and it's currently running. If it fails again I'll send you the directory structure untouched. Let me know if you spot something and I should kill and relaunch the params-issue.

**Comment by fmalmeida** [comment]
All seems to be ok. The error is very weird to me. But maybe making it does not fail when already existent can help on avoiding that ...

For the tree command, I actually need to see the untouched structure just when it fails 😄 so I can try to guess something.

Anyways, I am making this opting to always use fresh dirs available now in `params-issue` if you can restart with it to check if it helps 👍🏼
