### ISSUE TITLE
ERROR ~ Error executing process > 'HYBRID:strategy_2_wtdbg2 (ecoli_30X:strategy_2)'

### ISSUE THREAD

**Issue by sajjadasaf** [fmalmeida/MpGAP#76]
(mpgap-3.2) omic@omic-Precision-7920-Tower:~/Downloads/assembly$ nextflow run fmalmeida/mpgap   --output _ASSEMBLY   --max_cpus 5   --skip_spades   --input "samplesheet.yml"   --unicycler_additional_parameters ' --mode conservative '   -profile docker

 N E X T F L O W   ~  version 24.04.2

Launching `https://github.com/fmalmeida/mpgap` [mighty_mirzakhani] DSL2 - revision: 9f2475ff11 [master]

------------------------------------------------------
  fmalmeida/mpgap v3.2
------------------------------------------------------
Core Nextflow options
  revision                       : master
  runName                        : mighty_mirzakhani
  containerEngine                : docker
  container                      : [.*:fmalmeida/mpgap@sha256:d0c421d2caa6bfb6fbaad36b4182746485f750c82524b7b738b0d190505c8098]
  launchDir                      : /home/omic/Downloads/assembly
  workDir                        : /home/omic/Downloads/assembly/work
  projectDir                     : /home/omic/.nextflow/assets/fmalmeida/mpgap
  userName                       : omic
  profile                        : docker
  configFiles                    : /home/omic/.nextflow/assets/fmalmeida/mpgap/nextflow.config

Input/output options
  input                          : samplesheet.yml
  output                         : _ASSEMBLY

Computational options
  start_asm_mem                  : 20 GB
  max_cpus                       : 5
  max_memory                     : 40 GB

Turn assemblers and modules on/off
  skip_spades                    : true

Software' additional parameters
  unicycler_additional_parameters:  --mode conservative

Generic options
  tracedir                       : _ASSEMBLY/pipeline_info

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use fmalmeida/mpgap for your analysis please cite:

* The pipeline
  https://doi.org/10.12688/f1000research.139488.1

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/fmalmeida/mpgap#citation
------------------------------------------------------

    Launching defined workflows!
    By default, all workflows will appear in the console "log" message.
    However, the processes of each workflow will be launched based on the inputs received.
    You can see that processes that were not launched have an empty [-       ].
  
executor >  local (8)
[-        ] SHORTREADS_ONLY:unicycler                          -
[-        ] SHORTREADS_ONLY:shovill                            -
[-        ] SHORTREADS_ONLY:megahit                            -
[-        ] LONGREADS_ONLY:canu                                -
[-        ] LONGREADS_ONLY:flye                                -
[-        ] LONGREADS_ONLY:unicycler                           -
[-        ] LONGREADS_ONLY:raven                               -
[-        ] LONGREADS_ONLY:shasta                              -
[-        ] LONGREADS_ONLY:wtdbg2                              -
[-        ] LONGREADS_ONLY:hifiasm                             -
[-        ] LONGREADS_ONLY:medaka                              -
[-        ] LONGREADS_ONLY:nanopolish                          -
[-        ] LONGREADS_ONLY:gcpp                                -
[8c/80f386] HYBRID:strategy_1_unicycler (ecoli_30X:strategy_1) [  0%] 0 of 1
[7c/ee2d18] HYBRID:strategy_1_haslr (ecoli_30X:strategy_1)     [100%] 1 of 1, failed: 1 ✘
[1c/7053ec] HYBRID:strategy_2_canu (ecoli_30X:strategy_2)      [  0%] 0 of 1
[3c/9be87a] HYBRID:strategy_2_flye (ecoli_30X:strategy_2)      [  0%] 0 of 1 ✔
executor >  local (8)
[-        ] SHORTREADS_ONLY:unicycler                          -
[-        ] SHORTREADS_ONLY:shovill                            -
[-        ] SHORTREADS_ONLY:megahit                            -
[-        ] LONGREADS_ONLY:canu                                -
[-        ] LONGREADS_ONLY:flye                                -
[-        ] LONGREADS_ONLY:unicycler                           -
[-        ] LONGREADS_ONLY:raven                               -
[-        ] LONGREADS_ONLY:shasta                              -
[-        ] LONGREADS_ONLY:wtdbg2                              -
[-        ] LONGREADS_ONLY:hifiasm                             -
[-        ] LONGREADS_ONLY:medaka                              -
[-        ] LONGREADS_ONLY:nanopolish                          -
[-        ] LONGREADS_ONLY:gcpp                                -
[8c/80f386] HYBRID:strategy_1_unicycler (ecoli_30X:strategy_1) [100%] 1 of 1, failed: 1 ✘
[7c/ee2d18] HYBRID:strategy_1_haslr (ecoli_30X:strategy_1)     [100%] 1 of 1, failed: 1 ✘
[1c/7053ec] HYBRID:strategy_2_canu (ecoli_30X:strategy_2)      [100%] 1 of 1, failed: 1 ✘
[3c/9be87a] HYBRID:strategy_2_flye (ecoli_30X:strategy_2)      [100%] 1 of 1, failed: 1 ✘
[8a/54c676] HYBRID:strategy_2_unicycler (ecoli_30X:strategy_2) [100%] 1 of 1, failed: 1 ✘
[17/121160] HYBRID:strategy_2_raven (ecoli_30X:strategy_2)     [100%] 1 of 1, failed: 1 ✘
[e6/4fdd45] HYBRID:strategy_2_shasta (ecoli_30X:strategy_2)    [100%] 1 of 1, failed: 1 ✘
[-        ] HYBRID:strategy_2_hifiasm                          -
[83/f20e7f] HYBRID:strategy_2_wtdbg2 (ecoli_30X:strategy_2)    [100%] 1 of 1, failed: 1 ✘
executor >  local (8)
[-        ] SHORTREADS_ONLY:unicycler                          -
[-        ] SHORTREADS_ONLY:shovill                            -
[-        ] SHORTREADS_ONLY:megahit                            -
[-        ] LONGREADS_ONLY:canu                                -
[-        ] LONGREADS_ONLY:flye                                -
[-        ] LONGREADS_ONLY:unicycler                           -
[-        ] LONGREADS_ONLY:raven                               -
[-        ] LONGREADS_ONLY:shasta                              -
[-        ] LONGREADS_ONLY:wtdbg2                              -
[-        ] LONGREADS_ONLY:hifiasm                             -
[-        ] LONGREADS_ONLY:medaka                              -
[-        ] LONGREADS_ONLY:nanopolish                          -
[-        ] LONGREADS_ONLY:gcpp                                -
[8c/80f386] HYBRID:strategy_1_unicycler (ecoli_30X:strategy_1) [100%] 1 of 1, failed: 1 ✘
[7c/ee2d18] HYBRID:strategy_1_haslr (ecoli_30X:strategy_1)     [100%] 1 of 1, failed: 1 ✘
[1c/7053ec] HYBRID:strategy_2_canu (ecoli_30X:strategy_2)      [100%] 1 of 1, failed: 1 ✘
[3c/9be87a] HYBRID:strategy_2_flye (ecoli_30X:strategy_2)      [100%] 1 of 1, failed: 1 ✘
[8a/54c676] HYBRID:strategy_2_unicycler (ecoli_30X:strategy_2) [100%] 1 of 1, failed: 1 ✘
[17/121160] HYBRID:strategy_2_raven (ecoli_30X:strategy_2)     [100%] 1 of 1, failed: 1 ✘
[e6/4fdd45] HYBRID:strategy_2_shasta (ecoli_30X:strategy_2)    [100%] 1 of 1, failed: 1 ✘
[-        ] HYBRID:strategy_2_hifiasm                          -
[83/f20e7f] HYBRID:strategy_2_wtdbg2 (ecoli_30X:strategy_2)    [100%] 1 of 1, failed: 1 ✘
[-        ] HYBRID:strategy_2_medaka                           -
[-        ] HYBRID:strategy_2_nanopolish                       -
[-        ] HYBRID:strategy_2_gcpp                             -
[-        ] HYBRID:strategy_2_pilon                            -
[-        ] HYBRID:strategy_2_polypolish                       -
[-        ] ASSEMBLY_QC:quast                                  -
[-        ] ASSEMBLY_QC:CUSTOM_DUMPSOFTWAREVERSIONS            -
[-        ] ASSEMBLY_QC:multiqc                                -
Execution cancelled -- Finishing pending tasks before exit
Pipeline completed at: 2024-06-03T08:53:15.368670472+04:00
Execution status: failed
Execution duration: 5s
Do not give up, we can fix it!
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
ERROR ~ Error executing process > 'HYBRID:strategy_2_wtdbg2 (ecoli_30X:strategy_2)'

Caused by:
  Process `HYBRID:strategy_2_wtdbg2 (ecoli_30X:strategy_2)` terminated with an error exit status (127)

Command executed:

  # run wtdbg2
  wtdbg2.pl \
      -t 5 \
      -x ont \
      -g 4m \
      -o ecoli_30X \
       \
      SRX5299443_30X.fastq.gz
  
  # rename results
  cp ecoli_30X.cns.fa wtdbg2_assembly.fasta
  
  # get version
  # --version command does not exist
  cat <<-END_VERSIONS > versions.yml
  "HYBRID:strategy_2_wtdbg2":
      wtdbg2: 2.5
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 296: docker: command not found

Work dir:
  /home/omic/Downloads/assembly/work/83/f20e7fb57111d1073362c72536c288

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

**Comment by fmalmeida** [comment]
Hi @sajjadasaf ,
Thanks for trying the pipeline.
By the error, it seems you do not have Docker installed in your computer.

Is that the case? 

Cheers.

**Comment by sajjadasaf** [comment]
Thank you for your help. yes docker was the issue.

**Comment by fmalmeida** [comment]
Nice. I will close the issue then. Thanks.
